### ISSUE TITLE
problem with spaces inside charater classes [ xyz] 

### ISSUE THREAD

**Issue by grizzlysmit** [edumentab/p6-ecma262regex#5]
Hi I find that the **Regex** that is generated by `ECMA262Regex.compile( $rg );`  is very good but there is one fault if there is a space in a character class then it is translated like  this `[ -]?` ==> `<[ -]>?` which looks fine but will not match spaces because Raku ignores them, not sure if Raku should do that with a character class but it does so I am forced to do this 
```raku
$rg ~~ s:g/'[ -]' /[\\ -]/;
```
I tried 
```raku
$rg ~~ s:g/ '[' (.*) ' ' (.*) ']' /[$0\ $1]/;
```
but it only worked on one case guess I need to write a grammar for that :smirk: 

anyway I think the place to fix is in your parser :cowboy_hat_face:

**Comment by grizzlysmit** [comment]
I have devised  a better regex to fix the regex 
```raku
$rg               ~~ s:g/ '[' (<-[\ \x5D\x5B]>*) ' ' (<-[\x5D\x5B]>*) ']' /[$0\\ $1]/;
```
that works, but your grammar is still the logical place to fix this.

Note `\x5D is ]` and `\x5B is [`

**Comment by jnthn** [comment]
Thanks for the report. Suspect it might be more in the code-gen than the parsing. Will see if I can fix it this weekend.

**Comment by grizzlysmit** [comment]
thanks

**Comment by jnthn** [comment]
New release with fix shipped, and it's on the zef ecosystem now.
